=== shankar-trainer/hello-world/hcl_2023_1/XmlProject/customer.dtd
<!ELEMENT Customers (Customer+)>
<!ELEMENT Customer (id,name,salary,copyright,comment)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT salary (#PCDATA)>
<!ELEMENT copyright (#PCDATA)>
<!ELEMENT comment (#PCDATA)>
<!ATTLIST Customer ssn CDATA 'sr009'>

=== shankar-trainer/hello-world/hcl_2023_1/XmlProject/Customer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Customers SYSTEM "customer.dtd" >
<?xml-stylesheet type='text/css' href="Customer.css"?>
<Customers>
	<Customer ssn="0009">
		<id>1001</id>
		<name>mohan kumar</name>
		<salary>12000</salary>
		<copyright>&lt;abc.com&gt;</copyright>
		<comment>
		<![CDATA[
		  String var="hello";
		]]>

		</comment>
	</Customer>

	<Customer>
		<id>1002</id>
		<name>mohan kumar</name>
		<salary>12000</salary>
		<copyright>&lt;abc.com&gt;</copyright>
		<comment>
		<![CDATA[
		  document.write('hello world')
		  alert('welcome')
		]]>

		</comment>
	</Customer>


	<Customer ssn="sr0067">
		<id>1003</id>
		<name>mohan kumar</name>
		<salary>12000</salary>
		<copyright>&lt;abc.com&gt;</copyright>
		<comment></comment>

	</Customer>


</Customers>
