=== shankar-trainer/hello-world/xmlPrj/department.dtd
<!ELEMENT departments (department)+> 
<!ELEMENT department (id,name,location,state,pin,dept_info)> 
<!ELEMENT id  (#PCDATA)> 
<!ELEMENT name  (#PCDATA)> 
<!ELEMENT location  (#PCDATA)> 
<!ELEMENT state  (#PCDATA)> 
<!ELEMENT pin  (#PCDATA)> 
<!ELEMENT dept_info  (#PCDATA)> 
<!ATTLIST state state_id CDATA #REQUIRED>

<!ENTITY copyright "Copy Right Montran">
<!ENTITY writer "s kumar">

=== shankar-trainer/hello-world/xmlPrj/department.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE departments SYSTEM "department.dtd" >
<departments>
  <department>
    <id>767667</id>
    <name>training</name>
    <location>mumbai</location>
    <state state_id="566565">maharastra</state>
    <pin>75667767</pin>
    <dept_info>&copyright;&writer;</dept_info>
  </department>

  <department>
    <id>767667</id>
    <name>training</name>
    <location>mumbai</location>
    <state state_id="566565">maharastra</state>
    <pin>75667767</pin>
     <dept_info>&copyright;&writer;</dept_info>
  </department>
  
</departments>
