=== shankar-trainer/hello-world/gradle_ex/Test2/stud.dtd
<!ELEMENT student (stud,city)>
<!ELEMENT stud ((roll,name)|(name,roll))+>
<!ATTLIST stud id (1|2|3) #IMPLIED>
<!ELEMENT roll (#PCDATA)>
<!ELEMENT name ANY>
<!ELEMENT city EMPTY>

=== shankar-trainer/hello-world/gradle_ex/Test2/stud.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE student SYSTEM "stud.dtd">

<student>

<stud id="3">
<roll>1</roll>
<name>mohan</name>

<roll>1</roll>
<name>mohan</name>

</stud>

<city></city>

<stud id="2">
<name>sohan</name>
<roll>2</roll>
</stud>

<city></city>
 
</student>
