<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE customers [
        <!ELEMENT customers (customer)*>
        <!ELEMENT customer (id,name,salary)+>
        <!ELEMENT id (#PCDATA)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT salary (#PCDATA)>
        ]>
<customers>
    <customer>
        <id>10001</id>
        <name>amit kumar</name>
        <salary>30000</salary>
    </customer>
    <customer>
        <name>amit kumar</name>
        <id>10001</id>
        <salary>30000</salary>
    </customer>


</customers>
